# -*- coding: utf-8 -*-
"""
Created on Tue Aug 27 12:26:26 2024

@author: jacob
"""

import sys
sys.path.append('../common')
from Rxn_classes import Kinetiscope_simulation_reaction

"""
This script defines a function, build_index_reaction_dict, that creates a 
dictionary linking each reaction's index in a kinetiscope simulation to a 
Kinetiscope_simulation_reaction object, a class defined in Rxn_classes. Each 
object includes the reaction's name, a string identifier from the file, its 
index, and its selection frequency
"""

def remove_whitespace(name_with_whitespace):
    """
    Removes leading and trailing whitespace from a string.
    
    Parameters
    ----------
    name_with_whitespace : str
        The input string that may contain leading and/or trailing whitespace.
    
    Returns
    -------
    str
        The input string with leading and trailing whitespace removed.
    """
    
    name_without_left_space = name_with_whitespace.lstrip()
    name_without_whitespace = name_without_left_space.rstrip()
    
    return name_without_whitespace

def find_reaction_name(line):
    """
    Extracts and cleans the reaction name from a line of text.
    
    Parameters
    ----------
    line : str
        The input line of text that contains a reaction name, which is expected 
        to be after a colon (':').
    
    Returns
    -------
    str
        The reaction name with leading and trailing whitespace removed.
    """
    
    split_line = line.split(":")
    name_with_whitespace = split_line[1]
    
    return remove_whitespace(name_with_whitespace)

def build_k_sim_reaction(line, index, index_freq_dict):
    """
    Wrapper utility that generates a name for a given reaction and returns a
    Kinetiscope_simulation_reaction object.

    Parameters
    ----------
    line : str
        The line of text containing the reaction name, which will be extracted
        and cleaned.
    index : int
        The index associated with the reaction, used for identification.
    index_freq_dict : dict
        A dictionary mapping reaction indices to their selection frequencies. 
        The keys are indices (integers), and the values are selection frequencies (integers).

    Returns
    -------
    Kinetiscope_simulation_reaction
        A Kinetiscope_simulation_reaction object initialized with the cleaned 
        reaction name, the provided index, and the selection frequency from 
        index_freq_dict.

    """
    
    selection_freq = index_freq_dict.get(index, False)
    name = find_reaction_name(line)
    
    return Kinetiscope_simulation_reaction(name, index, selection_freq)

def build_index_reaction_dict(reaction_name_file, index_freq_dict):
    """
    Extracts reaction data from a file and constructs a dictionary of 
    Kinetiscope_simulation_reaction objects.
    
    Parameters
    ----------
    reaction_name_file : str
        The path to the file containing reaction names. Each line in the file 
        is expected to contain reaction data, with relevant information marked
        by "Equation".
    index_freq_dict : dict
        A dictionary mapping reaction indices to their selection frequencies. 
        The keys are indices (integers), and the values are selection 
        frequencies (integers). Generated by the build_index_freq_dict function.
    
    Returns
    -------
    dict
        A dictionary where keys are reaction indices (integers) and values are 
        Kinetiscope_simulation_reaction objects, created using the reaction 
        names from the file and the corresponding selection frequencies from 
        "index_freq_dict".
    """
    
    index_reaction_dict = {}
    index = 1
    
    with open(reaction_name_file, 'r') as file:
        for line in file:
            if "Equation" in line:
                
                k_sim_reaction = (
                    build_k_sim_reaction(line, index, index_freq_dict)
                )
                
                index_reaction_dict[index] = k_sim_reaction
                index += 1
                
    return index_reaction_dict